apiVersion: v2
name: loki
description: Grafana Loki log aggregation system
type: application
version: 0.1.0
appVersion: "2.9.4"

dependencies:
  - name: loki
    version: 6.6.2
    repository: https://grafana.github.io/helm-charts
