apiVersion: v2
name: tempo
description: A Helm chart for deploying Grafana Tempo
type: application
version: 0.1.0
appVersion: "1.5.0"

dependencies:
  - name: tempo
    version: 1.9.0
    repository: https://grafana.github.io/helm-charts
